### ISSUE TITLE
Please let me know about License.

### ISSUE THREAD

**Issue by MRamkee** [rubo77/table2CSV#15]
Please add license file, so that i can use this library.
Please let me know about License.

**Comment by rubo77** [comment]
This is open source and you can use is as you wish

**Comment by zmzhong** [comment]
@rubo77 Hi, could you please license your repo? I'm working on a project which only allows me to use open source code with approved licenses (e.g. The MIT License). 

From https://help.github.com/articles/licensing-a-repository/: 
"For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software. . . . without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license."

Thanks!

**Comment by rubo77** [comment]
Please create pr with a sitting licence. I don't want any special rights reserved. So I will probably accept a PR that adds a licence

**Comment by rubo77** [comment]
done
